export default Object.freeze({
  HOME: "Home",
  BOARDING: "Boarding",
  LOGIN: "Login",
  REGISTER: "Register",
  FORGET_PASSWORD: "Forget_Password",
  RESET_PASSWORD: "Reset_Password",
  CODE_VERIFICATION: "Code_Verification",
  MAP: "Map",
  REQUESTS: "Requests",
  SETTINGS_NAVIGATION: "Settings",
  PROFILE: "Profile",
  HOME_RIDER: "Home",
  PICK_UP: "Pick Up",
  VEHICLE_MANAGEMENT: "Vehicle Management",
  DOCUMENT_MANAGEMENT: "Document Management",
  REVIEWS: "Reviews",
  RANKING: "Ranking",
  LANGUAGE: "Language",
  NOTIFICATION: "Notifications",
  TERMS_PRIVACY: "Terms & Privacy Policy",
  CONTACT_US: "Contact Us",
  HISTORY: "History",
  INVITE_FRIENDS: "Invite Friends"
});
